### ISSUE TITLE
Make headers always compressed

### ISSUE THREAD

**Issue by LinuxJedi** [nginxinc/nginx-wiki#135]
when you scroll down you see the compressed header. It has been suggested that you should always see this header with the possibility of a mouseover showing the full header.

**Comment by pnommensen** [comment]
@LinuxJedi additional point here is that the "Free Trial" and "Contact Sales" buttons don't work. Perhaps they can be eliminated all together on the Wiki part of the website.

**Comment by LinuxJedi** [comment]
I suspect there is some JS I'm missing to capture that click. Your call, I can eliminate them or fix them
