### ISSUE TITLE
Anchor links are different to the old wiki

### ISSUE THREAD

**Issue by LinuxJedi** [nginxinc/nginx-wiki#139]
Reported by @agentzh 
The new wiki is substituting spaces and other characters for "-" whereas the old one used "_". The new wiki also substitutes ":" for "-" whereas the old one didn't.

We may not be able to easily fix Sphinx's anchor generator but we can add a regex in the old->new wiki redirect to cope with this.

I'll assign to me to investigate but may pass on to @aluttik if it involves the redirects.

**Comment by LinuxJedi** [comment]
Yep, this would require a large overhaul of sphinx to make the anchors the same. They are based on internal IDs so the changes would ripple though a lot of code.

Assigning to @aluttik to create a regex to go in the redirects. The regex needs to turn non-alphanumeric characters in anchor parts of the URL to dashes ('-').

**Comment by aluttik** [comment]
I'm a little confused. In the first comment, you say that the new wiki substitutes non-alphanumeric characters for dashes instead of underscores, and in the second comment you seem to be suggesting that that's the behavior we're looking for... Could you provide an example?

**Comment by agentzh** [comment]
@aluttik To quote my original report to @LinuxJedi :

> The in-page anchors are incompatible with the old wiki. For example
>
>    http://wiki.nginx.org/HttpLuaModule#lua_code_cache
>
> Now becomes
>
>    http://dev.wp.nginx.com/resources/wiki/modules/lua/#lua-code-cache
>
> Note the underscores are used in the former while dashes are used in the latter.
>
> Another example is
> http://wiki.nginx.org/HttpLuaModule#udpsock:settimeout becomes
> http://dev.wp.nginx.com/resources/wiki/modules/lua/#tcpsock-settimeout
> Please note how ":" becomes "-".
>
> Keeping the anchor names compatible is important since otherwise a lot
> of existing links are (sort of) broken.
> 
> Just a side note: I hope the auto redirect from wiki.nginx.org to the
> new wiki on nginx.com can take into account anchors carefully since
> many of my wiki pages are really big.

I think you can use the ngx_lua's manual on the old wiki as an example. We have various fancy characters in the section names :)

Thanks!

**Comment by LinuxJedi** [comment]
I was having a completely stupid moment is seems and @aluttik proved to me it isn't possible the way I wanted to do it. The anchor part of a URL is never sent to the server, it is client-side only. This means we need a client-side solution to this problem.

We either need to:

1. use JS on the new wiki to re-write the anchor
2. use JS on the new wiki to interpret the anchor and jump to the correct place
3. add some HTML and JS on the old wiki to re-write the anchor

I'm not sure if the first is possible, if it is I think that would be the preferred way of doing it. I'd rather not go down the third option route.

@aluttik if you want me to take this back and work on it let me know.
