### ISSUE TITLE
Errors in LUA documentation

### ISSUE THREAD

**Issue by LinuxJedi** [nginxinc/nginx-wiki#168]
From @agentzh:

"Here, &#91;[\\d+]] is stripped down to &#91;[\d+]] by the NGINX
config file parser and this is processed correctly."

The &#91; thing is really an artifact due to the migration.

**Comment by aluttik** [comment]
I'm confused... [[\d+]] is stripped down to [[\d+]]?

**Comment by LinuxJedi** [comment]
Sorry, GitHub messed up the quotation, try again:

```
"Here, &#91;[\\d+]] is stripped down to &#91;[\d+]] by the NGINX
config file parser and this is processed correctly."
```

I think the implication is that the html entities (the bits begining with '&') shouldn't be there
