### ISSUE TITLE
NGINX Plus for Google Cloud in Navigation

### ISSUE THREAD

**Issue by pnommensen** [nginxinc/nginx-wiki#172]
Hello, 

Please update the top/bottom navigation to include "NGINX Plus for Google Cloud" 

https://www.nginx.com/products/nginx-plus-google-cloud-platform/

**Comment by LinuxJedi** [comment]
there is no link to it on nginx.com's bottom nav. Update for top nav coming shortly

**Comment by pnommensen** [comment]
Thanks, bottom link is coming today.

**Comment by LinuxJedi** [comment]
Reopening due to waiting on bottom link

**Comment by pnommensen** [comment]
<img width="404" alt="screen shot 2015-10-06 at 5 16 51 pm" src="https://cloud.githubusercontent.com/assets/1695972/10326278/254e8286-6c4e-11e5-8ed1-031f6f8e4c53.png">
seems there is an additional green line below the title of the page on the dropdown.

**Comment by LinuxJedi** [comment]
ah, I thought that was intentional when I clicked on the nginx.com link you shared above. It appears that is supposed to be some kind of current page marker. I'll fix it today

**Comment by LinuxJedi** [comment]
ok, top nav fixed. Holding this open for bottom nav.
