### ISSUE TITLE
Some links are dead in the table

### ISSUE THREAD

**Issue by tenzan** [nginxinc/nginx-wiki#213]
Hi,

Some links are dead in the bottom table here
https://github.com/nginxinc/nginx-wiki/blob/master/source/index.rst

**Comment by LinuxJedi** [comment]
Hi,

Many thanks for opening this issue.

GitHub's .rst renderer cannot display those links correctly (and they are a bit of a hack). The end result is the four big buttons here: https://www.nginx.com/resources/wiki/

Unfortunately we don't have any control of GitHub's .rst parser so we can't fix how it displays this. We are going to have a redesign of the index page over the coming months which will probably work better with GitHub's rst parser.

Closing for now, please feel free to reopen if you think we missed something.
