### ISSUE TITLE
MediaWiki Recipe: Does Not Work - Blank White Page

### ISSUE THREAD

**Issue by teward** [nginxinc/nginx-wiki#235]
With the recipe provided here for MediaWiki, at https://github.com/nginxinc/nginx-wiki/blob/master/source/start/topics/recipes/mediawiki.rst, it fails to operate in latest Stable, and provides a blank page.

There is some type of unknown issue with this configuration as is - I tested the system to try and find errors, and could not.  This suggests the configuration does not work with the PHP content, for an unknown reason (no PHP errors, no errors in nginx).

**Comment by teward** [comment]
Opened here as a thread regarding issue in the recipe; note however I have found that extracting a PHP block from my fairly old WordPress configuration appears to have solved the blank page... not 100% sure why, but it does...

```
    location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            include fastcgi_params;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
    }
```

**Comment by LinuxJedi** [comment]
With some builds of NGINX I have found that SCRIPT_FILENAME isn't part of fastcgi_params. This has caused similar issues for me with other PHP sites. So the document should probably be updated to add that line.
