### ISSUE TITLE
404 Bad request receiving while accessing file.

### ISSUE THREAD

**Issue by manprajapat** [nginxinc/nginx-wiki#238]
file is accessing in web browser ( means file is downloading )
but in putty I can't access file.
error is : 

```
GET /gateway-versions/OGW_Ver12.bin HTTP1.1
HOST: 52.34.32.41<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

```

**Comment by LinuxJedi** [comment]
Hi,

Is this a specific problem with the wiki or with a server you are trying to talk to using NGINX.

If it is the wiki can you please let us know which section of the wiki you are referring to?

**Comment by manprajapat** [comment]
I was unable to find suitable wiki for this. my problem is related to accessing file on PUTTY.

**Comment by LinuxJedi** [comment]
This issues section is only for issues with the wiki source code, not for support with NGINX itself.

Please contact our mailing list http://mailman.nginx.org/mailman/listinfo/nginx or the NGINX Forum https://forum.nginx.org/ for community based help with this. Alternative you can contact the NGINX sales team to get paid-for support: https://www.nginx.com/
