### ISSUE TITLE
Building nginx with static openssl-1.0.2g on Mac OSX El Capitan 10.11.4 (15E65)

### ISSUE THREAD

**Issue by nVVEBd** [nginxinc/nginx-wiki#260]
Hi to all. Not sure if this is the right way to note this but here it goes:

I had a problem with nginx installation when I added the static library for OpenSSL:
./configure (options + path to static OpenSSL) would always take the ./config script of OpenSSL which would result in a make error.
I changed the "Makefile" in objs/Makefile under the OpenSSL section from `./config (options`) --->
to: `./Configure darwin64-x86_64-cc`
It would be good if the nginx configure script would detect this and push the command to the Makefile.

Just wanted to document this if someone finds himself/herself in the same postion.

**Comment by LinuxJedi** [comment]
Hi,

The correct place would be the NGINX public mailing list. But I will answer here. If you are doing the following you need to give the path to the OpenSSL source. The NGINX build system also builds OpenSSL:

```
./configure --with-openssl=/path/to/ssl
```

I should note that the OpenSSL that comes with MacOS is really old, you should probably try to use Homebrew's or the latest source.

Hope this helps.

**Comment by nVVEBd** [comment]
`./configure --with-openssl=/path/to/ssl/source` I used this. And I used the latest source. But nginx `./configure` prepares the openssl library to be configured with `./config` - which fails at make process - instead of 

> `./Configure darwin64-x86_64-cc`

which is the right configuration for El Capitan.

Thanks for replying before.

**Comment by LinuxJedi** [comment]
ah, I see. Please open an bug for this at https://trac.nginx.org/nginx/
