### ISSUE TITLE
WPMU WIki directs old style blogs.dir

### ISSUE THREAD

**Issue by inetbiz** [nginxinc/nginx-wiki#362]
https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/ WPMU gives directions for old style setup. I suggest blogs.dir be omitted and have new section for older WPMU installs when blogs.dir mattered?

**Comment by alessfg** [comment]
Sorry for the very late reply! Sadly, this is a community maintained wiki and not the appropriate venue for NGINX config questions. If you would like to submit a PR to make any relevant wiki changes, please go for it. Alternatively, if you have any config questions, I would recommend using the NGINX mailing list.
