### ISSUE TITLE
"Separate error logs" needs info on relative paths

### ISSUE THREAD

**Issue by gwideman** [nginxinc/nginx-wiki#380]
Page:
https://www.nginx.com/resources/wiki/start/topics/examples/separateerrorloggingpervirtualhost/

shows example config text with relative paths for the separate log files. There needs to be an explanation for:

1. What base path these paths are relative to.

2. What config file(s) these config statements belong in. I'm pretty sure they'd only apply to the site-specific config files in /etc/nginx/sites-available, but it should be spelled out.

**Comment by alessfg** [comment]
Sorry for the very late reply! Sadly, this is a community maintained wiki and not the appropriate venue for NGINX config questions. If you would like to submit a PR to make any relevant wiki changes, please go for it. Alternatively, if you have any config questions, I would recommend using the NGINX mailing list.

**Comment by gwideman** [comment]
> Sorry for the very late reply! Sadly, this is a community maintained wiki and not the appropriate venue for NGINX config questions. If you would like to submit a PR to make any relevant wiki changes, please go for it. Alternatively, if you have any config questions, I would recommend using the NGINX mailing list.

Alessandro -- I appreciate that you took the time to post a reply, and yes I realize the wiki is ostensibly community maintained. But your response does not address the issue, and it should not be closed.

First, the issue I posted is not a question per se. It points out a problem in the docs, which continues to be there 4+ years later. I can't make the "relevant wiki changes" because I don't know the answers. 

And the top level page for the NGINX wiki says "If you spot any problems please file a GitHub Issue." .. which is what I did. Which is how we got here.

**Comment by alessfg** [comment]
While I fully understand your understanding, the fact of the matter is that the wiki being community maintained does mean that the information is not always factual. I try to check PRs for correctness but it does look as if PRs from before my time did not check for correctness. Sadly -- and this relates to both your points -- the community maintained side of things means that as of today, any fixes also have to come from the community. That being said, things might change in the future 😄

**Comment by gwideman** [comment]
I appreciate your answer, and do understand that the wiki is maintained by the community.  And this is the github repo for the wiki. And this right here is the Issues section of that github repo. Where issues that the community might address should, I assume, be captured. Hence my reasoning that the issue should stay open in hopes that someone in the community may address it.  (I realize it's beyond your own scope for you to address all the issues.)

**Comment by heneil** [comment]
Hi @gwideman -- Hannah here, the community manager for nginx. This wiki has definitely been quiet for a while. Would you be open to talking about it? My email is h.neil@f5.com if so

**Comment by alessfg** [comment]
After due consideration we have gone ahead and decided to archive the wiki. The content will remain on the site and the GH repo for the time being, but the site will be taken down in due time. As it turns out, a 100% community maintained wiki does not really scale or maintain itself over time, and if we are going to produce technical docs, they might as well all live in a centralized docs site (https://docs.nginx.com).
