### ISSUE TITLE
redhatnginxinit.rst does not wait for worker thread to shut down

### ISSUE THREAD

**Issue by bschelling** [nginxinc/nginx-wiki#384]
the stop script in redhatnginxinit.rst does not wait for the worker thread to shut down which could take a while. i added a check for the process id still being available, but I'm not sure if this is the correct way to do it (see below)
any hints? 

```
 CurPID=$(<"$PIDFile")
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    while ps -p $CurPID  > /dev/null 
    do
       echo "nginx still running $CURPID";
       sleep 1
    done
    return $retval
```

**Comment by alessfg** [comment]
Sorry for the very late reply! Sadly, this is not the appropriate venue for NGINX config questions. I would recommend using the NGINX mailing list.
