### ISSUE TITLE
Drupal 8 Nginx custom redirect

### ISSUE THREAD

**Issue by Lulun10** [nginxinc/nginx-wiki#414]
Hi,

I have a Drupal 8 with a Nginx configuration. It’s work fine.
I want to add rewrite in Nginx from /news/2017-2018 to /news?saison=2017-2018.
I don’t know how to do this.
Can you help me ?

Thanks

**Comment by alessfg** [comment]
Sorry for the very late reply! Sadly, this is not the appropriate venue for NGINX config questions. I would recommend using the NGINX mailing list.
