### ISSUE TITLE
Good place for FastCGI unix socket

### ISSUE THREAD

**Issue by anon17** [nginxinc/nginx-wiki#426]
The mono example suggests to create socket in `/tmp`, which didn't work for me. Currently the preferred location for sockets per FHS is `/run`, but because web servers run under restricted account and `/run` is writable only by root, the FastCGI server package is supposed to install a folder `/run/myapp` with appropriate permissions and create socket there.
`/tmp` won't work because nginx service is configured by systemd to run on virtualized file system with private tmp, so it outright won't see global `/tmp`. `/var` won't work because selinux(?) audit thing ignores file permissions and denies access according to its own rules - can be seen in `/var/log/audit/audit.log`.

**Comment by alessfg** [comment]
Sorry for the very late reply! Sadly, this is not the appropriate venue for NGINX config questions. I would recommend using the NGINX mailing list.
