### ISSUE TITLE
installing nginx 

### ISSUE THREAD

**Issue by Easyschools** [nginxinc/nginx-wiki#427]
I am trying to install nginx to use it in for specific subdomains in cpanel. As i have two projects one is laravel and the other in angular. I want to make the laravel works with apache2 as backend and angular which is hosted by node server i want it to be hosted by nginx. I tried to install it using Engintron yesterday but it changed all my domains to use nginx as webserver. is there option that i can do make some folder work with apache2 and other folder with nginx. I have ordered another ip address so i can make apache2 work with ip different than the ip working with nginx. but when i tried to change domain ip address to the new one it is working but all the subdomains can't retrieve data  and says that ip is not configured. Although I have changed the virtual host ip in /var/cpanel/userdata/domain but still no luck. any help?

**Comment by alessfg** [comment]
Sorry for the very late reply! Sadly, this is not the appropriate venue for NGINX config questions. I would recommend using the NGINX mailing list.
