### ISSUE TITLE
Dynamic client certificate loading

### ISSUE THREAD

**Issue by bhavyabhatj** [nginxinc/nginx-wiki#481]
Hi ,
We are using nginx as a side car for our application for client certificate verification and chain validation.
Currently we have set the ca bundle to the known CA providers. 
But there is need that we would like to extend it for new CA for the client authentication. During this operation we would like to enable to the end user without having to redeploy the application which is running nginx as side car
Could you please guide how we can proceed with this requirement?

Here is our current set up:
server {      
  listen 8443 ssl;                               
  ssl_certificate /etc/nginx/certs/tls.crt;      
  ssl_certificate_key /etc/nginx/certs/tls.key;
  ssl_trusted_certificate /etc/nginx/certs/ca.pem;
  ssl_stapling on;
  ssl_verify_client optional_no_ca;
  ssl_stapling_verify on;
  ssl_verify_depth 2;        
  index index.html index.htm;
  
  location / {
   proxy_pass http://localhost:8080/;
   proxy_set_header x-activity-id $ssl_client_fingerprint;
   proxy_set_header X-SSL-CERT $ssl_client_escaped_cert;      
  }
}

**Comment by alessfg** [comment]
Hi @bhavyabhatj, 

Sadly, this is not the right place to ask configuration questions. I would recommend using any of the available community channels, either via sending an email to nginx@nginx.org or checking out the NGINX forum at https://forum.nginx.org.

Sorry about that, and best of luck with your NGINX configuration.

Cheers,
Alessandro.
