### ISSUE TITLE
If is not evil when used properly

### ISSUE THREAD

**Issue by bengalih** [nginxinc/nginx-wiki#508]
There is a lot of really bad misinformation being propagated by people who believe that "If is Evil" period.  This seemingly comes from the article:

https://github.com/nginxinc/nginx-wiki/blob/master/source/start/topics/depth/ifisevil.rst

While the first line of the article specifies the issue have to do with "if" in location context, and the body of the article explains fully, there are unfortunately people who don't read or verify their sources.  They see a title of an article like "lf is Evil" from the source and then assume everything they have been told about If being evil is true.

Can the name of this article be changed to be truthful and not sensationalist?  "If is Evil...used in location context" is an apt description of the article and would stop the spread of misinformation.

**Comment by alessfg** [comment]
I'm not opposed to changing the title -- can you submit a PR though? Should be as easy as tweaking the title in the `rst` file.

**Comment by bengalih** [comment]
Done.

https://github.com/nginxinc/nginx-wiki/pull/511

Thanks.
