### ISSUE TITLE
Code font makes tildes (~) look like hyphens (-)

### ISSUE THREAD

**Issue by mstrelan** [nginxinc/nginx-wiki#513]
For example: https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/

Courier 10 Pitch:
![image](https://user-images.githubusercontent.com/665110/83600469-01bac300-a5b2-11ea-86ad-93f4ada47e77.png)

DejaVu Sans Mono:
![image](https://user-images.githubusercontent.com/665110/83600612-45adc800-a5b2-11ea-9725-01fa49c907f7.png)

**Comment by arjenlentz** [comment]
Yes this is quite annoying.
Obviously once you know it's workable, but it'd just be better if this didn't happen.

Would suggest changing fonts for recipes.

**Comment by bdodsonf5com** [comment]
Hi there,
I'm trying to replicate this issue. Can you tell me what browsers you're using? 
Thanks

**Comment by mstrelan** [comment]
That was Firefox on Ubuntu 18.04. Can't reproduce on Android.

**Comment by bdodsonf5com** [comment]
Thanks!
