### ISSUE TITLE
Add descriptions for ngx_module_type options

### ISSUE THREAD

**Issue by EgoPingvina** [nginxinc/nginx-wiki#527]
Add, please, a description to options of `ngx_module_type` in [Config Shell File doc](https://github.com/nginxinc/nginx-wiki/blob/master/source/extending/new_config.rst).

> The type of module to build. Possible options are ``HTTP``, ``CORE``, ``HTTP_FILTER``, ``HTTP_INIT_FILTER``, ``HTTP_AUX_FILTER``, ``MAIL``, ``STREAM`` or ``MISC``

It say nothing for users. What's the difference between all of them?

**Comment by alessfg** [comment]
Hi @EgoPingvina! This wiki is community supported. I'll leave the issue open in case someone wants to address your question. FWIW, a simple explanation is that the module_type correlates to the context in which the module works/acts.
