### ISSUE TITLE
Suggestion: remove the IRC channel

### ISSUE THREAD

**Issue by c0fe** [nginxinc/nginx-wiki#544]
My suggestion may come across as extreme to some but after doing some research and talking to others I feel like unless Nginx themselves want to get involved then great but as it currently stands the nginx channel staff have a notorious history of being abusive to various members. My suggestion is simple, remove the portion of guiding the users to the IRC channel in its entirely and spare them of abuse.

**Comment by melbgirl** [comment]
Hi c0fe, thanks for the suggestion. I'm new to NGINX, brought in to help connect and support our open source community. Would mind connecting with me directly so I can learn more? You can reach me at l.meren@f5.com.

**Comment by c0fe** [comment]
@melbgirl email sent

**Comment by alessfg** [comment]
Hope this got addressed! We are archiving the Wiki but if it did not feel free to ping me and I'll connect you with the relevant people!
