### ISSUE TITLE
Mismatch in x-accel and xsendfile docs on trailing slash

### ISSUE THREAD

**Issue by mikehaertl** [nginxinc/nginx-wiki#563]
There is a minor mismatch on the documentation regarding the trailing slash.

In https://github.com/nginxinc/nginx-wiki/blob/master/source/start/topics/examples/xsendfile.rst a trailing slash is mentioned for `alias`:

> If you want to deliver /some/path/iso.img then configure NGINX like this:
> ```
> location /protected/ {
>   internal;
>   alias   /some/path/; # note the trailing slash
> }
> ```

Whereas on https://github.com/nginxinc/nginx-wiki/blob/master/source/start/topics/examples/x-accel.rst the trailing slash is not mentioned at all:

> Example configuration, notice the difference between alias and root.
> ```
> # Will serve /var/www/files/myfile.tar.gz
> # When passed URI /protected_files/myfile.tar.gz
> location /protected_files {
>   internal;
>   alias /var/www/files;
> }
> ```

This leaves me confused: Do we need the trailing slash or not?

**Comment by alessfg** [comment]
The tl;dr is that it depends. For the `location` directive, the trailing slash will determine how the location is matched (e.g. `/protected_files` will match `/protected_files_*` but `/protected/` will match `/protected/` as expected). For the `alias` directive, I'm going to reference the NGINX docs (https://nginx.org/en/docs/http/ngx_http_core_module.html#alias) and say that the standard is to include a trailing slash, as that explicitly declares that what you want to access is the content inside the given path.

**Comment by mikehaertl** [comment]
Right, but as I noted above both pages cover exactly the same topic: X-Acel/Xsendfile. And I think they should be consistent in their examples. To the reader it's confusing why the first page explicitely talks about adding the trailing slash (note, that I didn't add the comment after `alias` in the quote above) and the other page doesn't even mention it.

**Comment by alessfg** [comment]
I see your point. Feel free to submit a PR to make the change in that case 😄

**Comment by mikehaertl** [comment]
I could but I'm not sure how to fix this :). Actually I was searching for "Xsendfile Nginx" and was directed to the first page. Then from that page a link points to the documentation "in standard format" - which brought me to the second page.

I was expecting to find the usual Nginx documentation (like for `alias` that you linked) and was surprised to find mostly the same content on the second page - but noticed the difference in how they describe `alias`.

The main question to me: Why are there two pages at all? And is there an "official" documentation for this feature that could be linked?
