### ISSUE TITLE
[Doc] Drupal 8 nginx snippet

### ISSUE THREAD

**Issue by sticky-note** [nginxinc/nginx-wiki#568]
This commit f6e54f7862270600b0fc496d339e910f981be4e3 introduces bug as it makes web server to respond 404 to urls matching
```
/.*entries.*
/.*repository.*
/.*root.*
/.*tag.*
/.*template.*
/.*composer\.(json|lock).*
```
Drupal can have urls cointaing this subword in other urls and I think this behaviour is not intended
Previous version of this file already prevent access to `web.config`, `composer.lock` and `composer.json`

Please correct it as it is official documentation

**Comment by alessfg** [comment]
Can you create a PR? The wiki is 100% community supported.

**Comment by doublecompile** [comment]
I've added a pull request using the regular expression present in the latest version of `.htaccess` from the drupal/drupal project.
