### ISSUE TITLE
likeapache-htaccess.rst: Please also tell the nginx-alternative to .htaccess

### ISSUE THREAD

**Issue by schittli** [nginxinc/nginx-wiki#575]
Hello

This Page: https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/
explains why we should not use .htaccess
but the page does not tell which is the nginx alternative 😞 

#### Please keep in mind that .htaccess is great because 
1. the hosting provider can configure the webserver 
2. and the User can modify the webserver behaviour. 

Because nginx tells that we should not use .htaccess 
therefore I guess that users can add files named like `.nginx-config` to their website directories so that they can modify the default nginx behaviour?

Thanks a lot, kind regards,
Thomas

**Comment by alessfg** [comment]
There's a potentially relevant thread here https://stackoverflow.com/questions/35766676/how-can-i-use-an-htaccess-file-in-nginx

That being said, the wiki is exclusively maintained -- if you want to submit a PR that perhaps includes a link to that thread, please do!
