### ISSUE TITLE
How to SSL my http rpc on geth

### ISSUE THREAD

**Issue by kugimiya530** [nginxinc/nginx-wiki#587]
Hi i build a BSC fullnode 
and using example receipt make some modify for my port
I can using  /ws  and /rpc as well
but i got stuck few days for SSL rpc
from http:// to https://  
i do some search on google but still not work
can someone help me

server {

  listen 666;
  listen [::]:666;
  server_name localhost;

  location ^~ /ws {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass   http://127.0.0.1:8546/;
  }

  location ^~ /rpc {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass    http://127.0.0.1:8545/;
  }
}

I am tring to add  below code after server_name but it's didn't work
i have my ssl crt and key 

   ssl_certificate /etc/nginx/ssl/nginx.crt;
            ssl_certificate_key  /etc/nginx/ssl/nginx.key;
            ssl_session_timeout 5m;
            ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
            ssl_ciphers AESGCM:ALL:!DH:!EXPORT:!RC4:+HIGH:!MEDIUM:!LOW:!aNULL:!eNULL;
            ssl_prefer_server_ciphers on;

**Comment by alessfg** [comment]
Hey @kugimiya530! Thanks for reaching out but sadly this is not the appropriate venue for NGINX config questions. I would recommend using the NGINX mailing list.
