### ISSUE TITLE
how to limit conf's  IP amount

### ISSUE THREAD

**Issue by kugimiya530** [nginxinc/nginx-wiki#588]
I want to know which command can limit IP amount for each config

i am not mean "connections"

example  i want to limit 2 IP at same time
then
i can allow  X.X.X.X   Y.Y.Y.Y   two ip make  thousands connection
but  deny  X.X.X.X  Y.Y.Y.Y  Z.Z.Z.Z make  any  connections

**Comment by alessfg** [comment]
Thanks for reaching out but sadly this is not the appropriate venue for NGINX config questions. I would recommend using the NGINX mailing list.
