### ISSUE TITLE
Add authors section

### ISSUE THREAD

**Issue by LinuxJedi** [nginxinc/nginx-wiki#6]
There should be a page somewhere for everyone who contributes to name themselves along with any links about themselves.

**Comment by geerlingguy** [comment]
Is the contributors page in this repository not enough? https://github.com/nginxinc/nginx-wiki/graphs/contributors — maybe just a link to it would be adequate.

**Comment by LinuxJedi** [comment]
that is what I meant in my comment. I think that will be fine.

**Comment by SirNexus** [comment]
Old discussion was resolved. Closing now.
